name: Verify
on: [pull_request, push]


jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v4
  ls-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Install libraries
        run:
          npm run test